[common]
name = "Stage3_PST900" # name for this train session
gpu = 0

[dataset]
train = "data/dataset/PST900/train"
test = "data/dataset/PST900/test"
loader_threads = 8

[logging]
result_dir = 'data/results/' # fusion results, will be stored at data/results/%common.name%
write_result_freq = 50 # epochs or -1 to disable

[logging.tensorboard]
enabled = true
log_dir = 'data/tensorboard' # will be stored at data/tensorboard/%common.name%
log_image_freq = 50 # iterations or -1 to disable

[checkpoint]
path = 'data/checkpoint' # will be stored at data/checkpoint/%common.name%.pth
save_model_freq = 10 # epochs

[semseg]
config = 'config/pst900/segmodel-test.py'
model = 'data/checkpoint/segmodel.pth'
model_out = 'data/checkpoint/segmodel-0.pth'

[semseg.input]
# ImageNet values used by SegNeXt
mean = [0.485, 0.456, 0.406] # mean = [123.675, 116.28, 103.53]
std = [0.229, 0.224, 0.225] # std = [58.395, 57.12, 57.375]

[train]
stage = "III"
batch_size = 8
max_epochs = 126

[train.lr_scheduler.cosine]
policy = 'cosine'
T_0 = 1
T_mult = 2
min_lr = 1e-9

[train.lr_scheduler.linear_decay]
policy = 'linear_decay'
step = 20
gamma = 0.5

[hparam.lr.inner]
initial_lr = 1e-4

[hparam.lr.outer]
initial_lr = 1e-4

[hparam.lr.scheduler]
':ref' = 'train.lr_scheduler.cosine'

[hparam.loss_weight]
coeff_mse_loss_VF = 1.0 # alpha1
coeff_mse_loss_IF = 1.0
coeff_decomp = 2.0      # alpha2 and alpha4
coeff_tv = 5.0
weights_decomp = [1.0, 0.5, 0.2, 0.1]